// Type barrel for the KOEBELT design system.
//
// Two jobs:
//   1. Give the untyped .jsx components a single typed entry point.
//   2. Widen the four prop interfaces that declare no DOM attributes at all
//      (Icon, Quote, Checkbox, Switch) plus Button's anchor mode. The system's
//      own components already rely on props those interfaces omit — WorkRow.jsx
//      passes `style` to <Icon>, which would not typecheck unwidened.
//
// Widening happens HERE and never in the design system's own .d.ts files, which
// are regenerated by the design skill and would lose any edit.
//
// Specifiers are extensionless so TypeScript resolves each sibling .d.ts.

import * as React from "react";

import type { BadgeProps } from "./components/core/Badge";
import type { ButtonProps } from "./components/core/Button";
import type { DividerProps } from "./components/core/Divider";
import type { IconProps } from "./components/core/Icon";
import type { IconButtonProps } from "./components/core/IconButton";
import type { TagProps } from "./components/core/Tag";

import type { CheckboxProps } from "./components/forms/Checkbox";
import type { FieldProps } from "./components/forms/Field";
import type { InputProps } from "./components/forms/Input";
import type { SelectProps } from "./components/forms/Select";
import type { SwitchProps } from "./components/forms/Switch";
import type { TextareaProps } from "./components/forms/Textarea";

import type { CardProps } from "./components/content/Card";
import type { MediaFrameProps } from "./components/content/MediaFrame";
import type { ProjectCardProps } from "./components/content/ProjectCard";
import type { QuoteProps } from "./components/content/Quote";
import type { SectionHeadingProps } from "./components/content/SectionHeading";
import type { WorkRowProps } from "./components/content/WorkRow";

import type { LogoProps } from "./components/brand/Logo";
import type { MarqueeProps } from "./components/brand/Marquee";

import type { FooterBarProps } from "./components/navigation/FooterBar";
import type { NavBarProps } from "./components/navigation/NavBar";
import type { TabsProps } from "./components/navigation/Tabs";

import type { DialogProps } from "./components/feedback/Dialog";
import type { NoticeProps } from "./components/feedback/Notice";

/** Every component spreads `...rest` onto its root node and merges `style` last. */
type DOMish<E = HTMLElement> = React.HTMLAttributes<E> & { key?: React.Key };

export type { BadgeProps, ButtonProps, DividerProps, IconProps, IconButtonProps, TagProps };
export type { CheckboxProps, FieldProps, InputProps, SelectProps, SwitchProps, TextareaProps };
export type { CardProps, MediaFrameProps, ProjectCardProps, QuoteProps, SectionHeadingProps, WorkRowProps };
export type { LogoProps, MarqueeProps };
export type { FooterBarProps, NavBarProps, TabsProps };
export type { DialogProps, NoticeProps };

// core
export declare function Badge(props: BadgeProps): React.JSX.Element;
/** `as="a"` turns this into an anchor, so anchor attributes (href, download, target) apply. */
export declare function Button(
  props: ButtonProps & Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, "type">,
): React.JSX.Element;
export declare function Divider(props: DividerProps): React.JSX.Element;
/** IconProps declares no DOM attributes; widened here (WorkRow.jsx already passes `style`). */
export declare function Icon(props: IconProps & React.SVGAttributes<SVGSVGElement>): React.JSX.Element;
export declare function IconButton(
  props: IconButtonProps & Pick<React.AnchorHTMLAttributes<HTMLAnchorElement>, "href" | "target" | "rel">,
): React.JSX.Element;
export declare function Tag(props: TagProps): React.JSX.Element;
export declare const ICONS: Record<string, string[]>;

// forms
export declare function Checkbox(props: CheckboxProps & DOMish<HTMLLabelElement>): React.JSX.Element;
export declare function Field(props: FieldProps): React.JSX.Element;
export declare function Input(props: InputProps): React.JSX.Element;
export declare function Select(props: SelectProps): React.JSX.Element;
export declare function Switch(props: SwitchProps & DOMish<HTMLLabelElement>): React.JSX.Element;
export declare function Textarea(props: TextareaProps): React.JSX.Element;

// content
export declare function Card(props: CardProps): React.JSX.Element;
export declare function MediaFrame(props: MediaFrameProps): React.JSX.Element;
export declare function ProjectCard(props: ProjectCardProps): React.JSX.Element;
export declare function Quote(props: QuoteProps & DOMish<HTMLQuoteElement>): React.JSX.Element;
export declare function SectionHeading(props: SectionHeadingProps): React.JSX.Element;
export declare function WorkRow(props: WorkRowProps): React.JSX.Element;

// brand
export declare function Logo(props: LogoProps): React.JSX.Element;
export declare function Marquee(props: MarqueeProps): React.JSX.Element;

// navigation
export declare function FooterBar(props: FooterBarProps): React.JSX.Element;
export declare function NavBar(props: NavBarProps): React.JSX.Element;
export declare function Tabs(props: TabsProps): React.JSX.Element;

// feedback
export declare function Dialog(props: DialogProps): React.JSX.Element;
export declare function Notice(props: NoticeProps): React.JSX.Element;
