name: languages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Languages percentages
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.languages.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_languages: yes
