name: languages

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Featured star list languages
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        plugin_languages: yes
        plugin_languages_threshold: 2%
